#include "runtime_asm.hpp"
#include <ostream>

namespace RuntimeASM {
void emit(std::ostream& out) {
    out << "section .data\n"
        << "    global_heap: times 4096 db 0\n"
        << "    global_heap_end:\n"
        << "    heap_pointer: dq global_heap\n"
        << "    newline: db 10\n\n";
    out << "section .text\nglobal _start\n\n";
    out << "_start:\n    call main\n    mov rdi, rax\n    shr rdi, 1\n    mov rax, 60\n    syscall\n\n";
    out << "Runtime_alloc:\n"
        << "    mov rax, [heap_pointer]\n"
        << "    lea rcx, [rax + rdi]\n"
        << "    cmp rcx, global_heap_end\n"
        << "    ja Runtime_heap_overflow\n"
        << "    mov [heap_pointer], rcx\n"
        << "    ret\n\n"
        << "Runtime_heap_overflow:\n"
        << "    mov rdi, 255\n"
        << "    mov rax, 60\n"
        << "    syscall\n\n";
    out << "Runtime_bounds_error:\n"
        << "    mov rdi, 254\n"
        << "    mov rax, 60\n"
        << "    syscall\n\n";
    out << "Runtime_print:\n"
        << "    mov rdx, [rdi + 8]\n"
        << "    mov rsi, [rdi + 16]\n"
        << "    mov rdi, 1\n"
        << "    mov rax, 1\n"
        << "    syscall\n"
        << "    mov rdx, 1\n"
        << "    mov rsi, newline\n"
        << "    mov rdi, 1\n"
        << "    mov rax, 1\n"
        << "    syscall\n"
        << "    mov rax, 1\n"
        << "    ret\n\n";
    out << "Runtime_readLine:\n"
        << "    mov rdi, 1048\n"
        << "    call Runtime_alloc\n"
        << "    mov rbx, rax\n"
        << "    mov qword [rbx], 0\n"
        << "    xor r8, r8\n"
        << ".L_readLine_loop:\n"
        << "    cmp r8, 1024\n"
        << "    jge .L_readLine_done\n"
        << "    xor rax, rax\n"
        << "    xor rdi, rdi\n"
        << "    lea rsi, [rbx + 24 + r8]\n"
        << "    mov rdx, 1\n"
        << "    syscall\n"
        << "    cmp rax, 1\n"
        << "    jne .L_readLine_done\n"
        << "    cmp byte [rsi], 10\n"
        << "    je .L_readLine_done\n"
        << "    inc r8\n"
        << "    jmp .L_readLine_loop\n"
        << ".L_readLine_done:\n"
        << "    mov [rbx + 8], r8\n"
        << "    lea rax, [rbx + 24]\n"
        << "    mov [rbx + 16], rax\n"
        << "    mov rax, rbx\n"
        << "    ret\n\n";
    out << "Int_method_toString:\n"
        << "    mov r10, rdi\n"
        << "    mov rdi, 56\n"
        << "    call Runtime_alloc\n"
        << "    mov rbx, rax\n"
        << "    mov rax, r10\n"
        << "    sar rax, 1\n"
        << "    mov qword [rbx], 0\n"
        << "    mov rcx, 10\n"
        << "    lea rsi, [rbx + 56]\n"
        << "    xor r8, r8\n"
        << "    xor r9, r9\n"
        << "    test rax, rax\n"
        << "    jge .L_str_abs_ready\n"
        << "    neg rax\n"
        << "    mov r9, 1\n"
        << ".L_str_abs_ready:\n"
        << "    test rax, rax\n"
        << "    jnz .L_loop_str\n"
        << "    dec rsi\n"
        << "    inc r8\n"
        << "    mov byte [rsi], 0x30\n"
        << "    jmp .L_str_sign\n"
        << ".L_loop_str:\n"
        << "    dec rsi\n"
        << "    inc r8\n"
        << "    cqo\n"
        << "    idiv rcx\n"
        << "    add dl, 0x30\n"
        << "    mov [rsi], dl\n"
        << "    test rax, rax\n"
        << "    jnz .L_loop_str\n"
        << ".L_str_sign:\n"
        << "    test r9, r9\n"
        << "    jz .L_str_done\n"
        << "    dec rsi\n"
        << "    inc r8\n"
        << "    mov byte [rsi], 0x2d\n"
        << ".L_str_done:\n"
        << "    mov [rbx + 8], r8\n"
        << "    mov [rbx + 16], rsi\n"
        << "    mov rax, rbx\n"
        << "    ret\n\n";
}
}
