#include "runtime_asm.hpp"
#include <ostream>

namespace RuntimeASM {
void emit(std::ostream& out) {
    out << "section .data\n"
        << "    global_heap: times 4096 db 0\n"
        << "    global_heap_end:\n"
        << "    heap_pointer: dq global_heap\n"
        << "    newline: db 10\n\n";
    out << "section .text\nglobal _start\n\n";
    out << "_start:\n    call main\n    mov rdi, rax\n    shr rdi, 1\n    mov rax, 60\n    syscall\n\n";
    out << "Runtime_alloc:\n"
        << "    mov rax, [heap_pointer]\n"
        << "    lea rcx, [rax + rdi]\n"
        << "    cmp rcx, global_heap_end\n"
        << "    ja Runtime_heap_overflow\n"
        << "    mov [heap_pointer], rcx\n"
        << "    ret\n\n"
        << "Runtime_heap_overflow:\n"
        << "    mov rdi, 255\n"
        << "    mov rax, 60\n"
        << "    syscall\n\n";
    out << "Runtime_bounds_error:\n"
        << "    mov rdi, 254\n"
        << "    mov rax, 60\n"
        << "    syscall\n\n";
    out << "Runtime_parse_error:\n"
        << "    mov rdi, 253\n"
        << "    mov rax, 60\n"
        << "    syscall\n\n";
    out << "Runtime_print:\n"
        << "    mov rdx, [rdi + 8]\n"
        << "    mov rsi, [rdi + 16]\n"
        << "    mov rdi, 1\n"
        << "    mov rax, 1\n"
        << "    syscall\n"
        << "    mov rdx, 1\n"
        << "    mov rsi, newline\n"
        << "    mov rdi, 1\n"
        << "    mov rax, 1\n"
        << "    syscall\n"
        << "    mov rax, 1\n"
        << "    ret\n\n";
    out << "Runtime_readLine:\n"
        << "    mov rdi, 1048\n"
        << "    call Runtime_alloc\n"
        << "    mov rbx, rax\n"
        << "    mov qword [rbx], 0\n"
        << "    xor r8, r8\n"
        << ".L_readLine_loop:\n"
        << "    cmp r8, 1024\n"
        << "    jge .L_readLine_done\n"
        << "    xor rax, rax\n"
        << "    xor rdi, rdi\n"
        << "    lea rsi, [rbx + 24 + r8]\n"
        << "    mov rdx, 1\n"
        << "    syscall\n"
        << "    cmp rax, 1\n"
        << "    jne .L_readLine_done\n"
        << "    cmp byte [rsi], 10\n"
        << "    je .L_readLine_done\n"
        << "    inc r8\n"
        << "    jmp .L_readLine_loop\n"
        << ".L_readLine_done:\n"
        << "    mov [rbx + 8], r8\n"
        << "    lea rax, [rbx + 24]\n"
        << "    mov [rbx + 16], rax\n"
        << "    mov rax, rbx\n"
        << "    ret\n\n";
    out << "Runtime_stringEquals:\n"
        << "    mov rax, [rdi + 8]\n"
        << "    cmp rax, [rsi + 8]\n"
        << "    jne .L_string_equals_false\n"
        << "    mov rcx, rax\n"
        << "    mov r8, [rdi + 16]\n"
        << "    mov r9, [rsi + 16]\n"
        << ".L_string_equals_loop:\n"
        << "    test rcx, rcx\n"
        << "    je .L_string_equals_true\n"
        << "    mov al, [r8]\n"
        << "    cmp al, [r9]\n"
        << "    jne .L_string_equals_false\n"
        << "    inc r8\n"
        << "    inc r9\n"
        << "    dec rcx\n"
        << "    jmp .L_string_equals_loop\n"
        << ".L_string_equals_true:\n"
        << "    mov rax, 3\n"
        << "    ret\n"
        << ".L_string_equals_false:\n"
        << "    mov rax, 1\n"
        << "    ret\n\n";
    out << "Runtime_stringStartsWith:\n"
        << "    mov rax, [rsi + 8]\n"
        << "    cmp qword [rdi + 8], rax\n"
        << "    jl .L_string_starts_false\n"
        << "    mov rcx, rax\n"
        << "    mov r8, [rdi + 16]\n"
        << "    mov r9, [rsi + 16]\n"
        << ".L_string_starts_loop:\n"
        << "    test rcx, rcx\n"
        << "    je .L_string_starts_true\n"
        << "    mov al, [r8]\n"
        << "    cmp al, [r9]\n"
        << "    jne .L_string_starts_false\n"
        << "    inc r8\n"
        << "    inc r9\n"
        << "    dec rcx\n"
        << "    jmp .L_string_starts_loop\n"
        << ".L_string_starts_true:\n"
        << "    mov rax, 3\n"
        << "    ret\n"
        << ".L_string_starts_false:\n"
        << "    mov rax, 1\n"
        << "    ret\n\n";
    out << "Runtime_stringToInt:\n"
        << "    mov rdx, [rdi + 8]\n"
        << "    mov rsi, [rdi + 16]\n"
        << "    test rdx, rdx\n"
        << "    je Runtime_parse_error\n"
        << "    xor rax, rax\n"
        << "    xor rcx, rcx\n"
        << "    xor r8, r8\n"
        << "    cmp byte [rsi], 0x2d\n"
        << "    jne .L_string_to_int_loop\n"
        << "    mov r8, 1\n"
        << "    inc rcx\n"
        << "    cmp rcx, rdx\n"
        << "    je Runtime_parse_error\n"
        << ".L_string_to_int_loop:\n"
        << "    cmp rcx, rdx\n"
        << "    jge .L_string_to_int_done\n"
        << "    movzx r9, byte [rsi + rcx]\n"
        << "    cmp r9b, 0x30\n"
        << "    jb Runtime_parse_error\n"
        << "    cmp r9b, 0x39\n"
        << "    ja Runtime_parse_error\n"
        << "    imul rax, rax, 10\n"
        << "    sub r9, 0x30\n"
        << "    add rax, r9\n"
        << "    inc rcx\n"
        << "    jmp .L_string_to_int_loop\n"
        << ".L_string_to_int_done:\n"
        << "    test r8, r8\n"
        << "    jz .L_string_to_int_tag\n"
        << "    neg rax\n"
        << ".L_string_to_int_tag:\n"
        << "    shl rax, 1\n"
        << "    or rax, 1\n"
        << "    ret\n\n";
    out << "Runtime_stringToCharArray:\n"
        << "    mov r11, [rdi + 8]\n"
        << "    mov r10, [rdi + 16]\n"
        << "    lea rdi, [r11 * 8 + 16]\n"
        << "    call Runtime_alloc\n"
        << "    mov rbx, rax\n"
        << "    mov qword [rbx], 0\n"
        << "    mov rax, r11\n"
        << "    shl rax, 1\n"
        << "    or rax, 1\n"
        << "    mov [rbx + 8], rax\n"
        << "    xor rcx, rcx\n"
        << ".L_string_to_char_array_loop:\n"
        << "    cmp rcx, r11\n"
        << "    jge .L_string_to_char_array_wrap\n"
        << "    movzx rax, byte [r10 + rcx]\n"
        << "    shl rax, 1\n"
        << "    or rax, 1\n"
        << "    mov [rbx + 16 + rcx * 8], rax\n"
        << "    inc rcx\n"
        << "    jmp .L_string_to_char_array_loop\n"
        << ".L_string_to_char_array_wrap:\n"
        << "    mov rdi, 16\n"
        << "    call Runtime_alloc\n"
        << "    mov qword [rax], 0\n"
        << "    mov [rax + 8], rbx\n"
        << "    ret\n\n";
    out << "Int_method_toString:\n"
        << "    mov r10, rdi\n"
        << "    mov rdi, 56\n"
        << "    call Runtime_alloc\n"
        << "    mov rbx, rax\n"
        << "    mov rax, r10\n"
        << "    sar rax, 1\n"
        << "    mov qword [rbx], 0\n"
        << "    mov rcx, 10\n"
        << "    lea rsi, [rbx + 56]\n"
        << "    xor r8, r8\n"
        << "    xor r9, r9\n"
        << "    test rax, rax\n"
        << "    jge .L_str_abs_ready\n"
        << "    neg rax\n"
        << "    mov r9, 1\n"
        << ".L_str_abs_ready:\n"
        << "    test rax, rax\n"
        << "    jnz .L_loop_str\n"
        << "    dec rsi\n"
        << "    inc r8\n"
        << "    mov byte [rsi], 0x30\n"
        << "    jmp .L_str_sign\n"
        << ".L_loop_str:\n"
        << "    dec rsi\n"
        << "    inc r8\n"
        << "    cqo\n"
        << "    idiv rcx\n"
        << "    add dl, 0x30\n"
        << "    mov [rsi], dl\n"
        << "    test rax, rax\n"
        << "    jnz .L_loop_str\n"
        << ".L_str_sign:\n"
        << "    test r9, r9\n"
        << "    jz .L_str_done\n"
        << "    dec rsi\n"
        << "    inc r8\n"
        << "    mov byte [rsi], 0x2d\n"
        << ".L_str_done:\n"
        << "    mov [rbx + 8], r8\n"
        << "    mov [rbx + 16], rsi\n"
        << "    mov rax, rbx\n"
        << "    ret\n\n";
}
}
