#include "runtime_asm.hpp"
#include <ostream>

namespace RuntimeASM {
void emit(std::ostream& out) {
    out << "section .data\n"
        << "    global_heap: times 65536 db 0\n"
        << "    global_heap_end:\n"
        << "    heap_pointer: dq global_heap\n"
        << "    newline: db 10\n\n";
    out << "section .text\nglobal _start\n\n";
    out << "_start:\n    call main\n    mov rdi, rax\n    shr rdi, 1\n    mov rax, 60\n    syscall\n\n";
    out << "Runtime_alloc:\n"
        << "    mov rax, [heap_pointer]\n"
        << "    lea rcx, [rax + rdi]\n"
        << "    cmp rcx, global_heap_end\n"
        << "    ja Runtime_heap_overflow\n"
        << "    mov [heap_pointer], rcx\n"
        << "    ret\n\n"
        << "Runtime_heap_overflow:\n"
        << "    mov rdi, 255\n"
        << "    mov rax, 60\n"
        << "    syscall\n\n";
    out << "Runtime_bounds_error:\n"
        << "    mov rdi, 254\n"
        << "    mov rax, 60\n"
        << "    syscall\n\n";
    out << "Runtime_parse_error:\n"
        << "    mov rdi, 253\n"
        << "    mov rax, 60\n"
        << "    syscall\n\n";
    out << "Runtime_print:\n"
        << "    mov rdx, [rdi + 8]\n"
        << "    mov rsi, [rdi + 16]\n"
        << "    mov rdi, 1\n"
        << "    mov rax, 1\n"
        << "    syscall\n"
        << "    mov rdx, 1\n"
        << "    mov rsi, newline\n"
        << "    mov rdi, 1\n"
        << "    mov rax, 1\n"
        << "    syscall\n"
        << "    mov rax, 1\n"
        << "    ret\n\n";
    out << "Runtime_readLine:\n"
        << "    mov rdi, 1048\n"
        << "    call Runtime_alloc\n"
        << "    mov rbx, rax\n"
        << "    mov qword [rbx], 0\n"
        << "    xor r8, r8\n"
        << ".L_readLine_loop:\n"
        << "    cmp r8, 1024\n"
        << "    jge .L_readLine_done\n"
        << "    xor rax, rax\n"
        << "    xor rdi, rdi\n"
        << "    lea rsi, [rbx + 24 + r8]\n"
        << "    mov rdx, 1\n"
        << "    syscall\n"
        << "    cmp rax, 1\n"
        << "    jne .L_readLine_done\n"
        << "    cmp byte [rsi], 10\n"
        << "    je .L_readLine_done\n"
        << "    inc r8\n"
        << "    jmp .L_readLine_loop\n"
        << ".L_readLine_done:\n"
        << "    mov [rbx + 8], r8\n"
        << "    lea rax, [rbx + 24]\n"
        << "    mov [rbx + 16], rax\n"
        << "    mov rax, rbx\n"
        << "    ret\n\n";
    out << "Runtime_copyPathToCString:\n"
        << "    mov r10, rdi\n"
        << "    mov r11, [r10 + 8]\n"
        << "    mov rdi, r11\n"
        << "    inc rdi\n"
        << "    call Runtime_alloc\n"
        << "    mov rbx, rax\n"
        << "    mov r8, [r10 + 16]\n"
        << "    xor rcx, rcx\n"
        << ".L_copy_path_loop:\n"
        << "    cmp rcx, r11\n"
        << "    jge .L_copy_path_done\n"
        << "    mov al, [r8 + rcx]\n"
        << "    mov [rbx + rcx], al\n"
        << "    inc rcx\n"
        << "    jmp .L_copy_path_loop\n"
        << ".L_copy_path_done:\n"
        << "    mov byte [rbx + r11], 0\n"
        << "    mov rax, rbx\n"
        << "    ret\n\n";
    out << "Runtime_emptyString:\n"
        << "    mov rdi, 24\n"
        << "    call Runtime_alloc\n"
        << "    mov qword [rax], 0\n"
        << "    mov qword [rax + 8], 0\n"
        << "    lea rbx, [rax + 24]\n"
        << "    mov [rax + 16], rbx\n"
        << "    ret\n\n";
    out << "Runtime_readFile:\n"
        << "    call Runtime_copyPathToCString\n"
        << "    mov rdi, rax\n"
        << "    xor rsi, rsi\n"
        << "    xor rdx, rdx\n"
        << "    mov rax, 2\n"
        << "    syscall\n"
        << "    cmp rax, 0\n"
        << "    jl Runtime_emptyString\n"
        << "    mov r13, rax\n"
        << "    mov rdi, r13\n"
        << "    xor rsi, rsi\n"
        << "    mov rdx, 2\n"
        << "    mov rax, 8\n"
        << "    syscall\n"
        << "    cmp rax, 0\n"
        << "    jl .L_read_file_close_empty\n"
        << "    mov r14, rax\n"
        << "    mov rdi, r13\n"
        << "    xor rsi, rsi\n"
        << "    xor rdx, rdx\n"
        << "    mov rax, 8\n"
        << "    syscall\n"
        << "    cmp rax, 0\n"
        << "    jl .L_read_file_close_empty\n"
        << "    mov rdi, r14\n"
        << "    add rdi, 24\n"
        << "    call Runtime_alloc\n"
        << "    mov r15, rax\n"
        << "    mov qword [r15], 0\n"
        << "    mov qword [r15 + 8], 0\n"
        << "    lea rbx, [r15 + 24]\n"
        << "    mov [r15 + 16], rbx\n"
        << "    xor r12, r12\n"
        << ".L_read_file_loop:\n"
        << "    cmp r12, r14\n"
        << "    jge .L_read_file_done\n"
        << "    mov rdi, r13\n"
        << "    mov rsi, [r15 + 16]\n"
        << "    add rsi, r12\n"
        << "    mov rdx, r14\n"
        << "    sub rdx, r12\n"
        << "    xor rax, rax\n"
        << "    syscall\n"
        << "    cmp rax, 0\n"
        << "    jl .L_read_file_close_empty\n"
        << "    je .L_read_file_done\n"
        << "    add r12, rax\n"
        << "    jmp .L_read_file_loop\n"
        << ".L_read_file_done:\n"
        << "    mov [r15 + 8], r12\n"
        << "    mov rdi, r13\n"
        << "    mov rax, 3\n"
        << "    syscall\n"
        << "    mov rax, r15\n"
        << "    ret\n"
        << ".L_read_file_close_empty:\n"
        << "    mov rdi, r13\n"
        << "    mov rax, 3\n"
        << "    syscall\n"
        << "    jmp Runtime_emptyString\n\n";
    out << "Runtime_writeFile:\n"
        << "    mov r12, rsi\n"
        << "    call Runtime_copyPathToCString\n"
        << "    mov rdi, rax\n"
        << "    mov rsi, 577\n"
        << "    mov rdx, 420\n"
        << "    mov rax, 2\n"
        << "    syscall\n"
        << "    cmp rax, 0\n"
        << "    jl .L_write_file_return_tagged\n"
        << "    mov r13, rax\n"
        << "    mov rdi, r13\n"
        << "    mov rsi, [r12 + 16]\n"
        << "    mov rdx, [r12 + 8]\n"
        << "    mov rax, 1\n"
        << "    syscall\n"
        << "    mov r14, rax\n"
        << "    mov rdi, r13\n"
        << "    mov rax, 3\n"
        << "    syscall\n"
        << "    mov rax, r14\n"
        << ".L_write_file_return_tagged:\n"
        << "    shl rax, 1\n"
        << "    or rax, 1\n"
        << "    ret\n\n";
    out << "Runtime_appendFile:\n"
        << "    mov r12, rsi\n"
        << "    call Runtime_copyPathToCString\n"
        << "    mov rdi, rax\n"
        << "    mov rsi, 1089\n"
        << "    mov rdx, 420\n"
        << "    mov rax, 2\n"
        << "    syscall\n"
        << "    cmp rax, 0\n"
        << "    jl .L_append_file_return_tagged\n"
        << "    mov r13, rax\n"
        << "    mov rdi, r13\n"
        << "    mov rsi, [r12 + 16]\n"
        << "    mov rdx, [r12 + 8]\n"
        << "    mov rax, 1\n"
        << "    syscall\n"
        << "    mov r14, rax\n"
        << "    mov rdi, r13\n"
        << "    mov rax, 3\n"
        << "    syscall\n"
        << "    mov rax, r14\n"
        << ".L_append_file_return_tagged:\n"
        << "    shl rax, 1\n"
        << "    or rax, 1\n"
        << "    ret\n\n";
    out << "Runtime_fileExists:\n"
        << "    call Runtime_copyPathToCString\n"
        << "    mov rdi, rax\n"
        << "    xor rsi, rsi\n"
        << "    xor rdx, rdx\n"
        << "    mov rax, 2\n"
        << "    syscall\n"
        << "    cmp rax, 0\n"
        << "    jl .L_file_exists_false\n"
        << "    mov r13, rax\n"
        << "    mov rdi, r13\n"
        << "    mov rax, 3\n"
        << "    syscall\n"
        << "    mov rax, 3\n"
        << "    ret\n"
        << ".L_file_exists_false:\n"
        << "    mov rax, 1\n"
        << "    ret\n\n";
    out << "Runtime_stringEquals:\n"
        << "    mov rax, [rdi + 8]\n"
        << "    cmp rax, [rsi + 8]\n"
        << "    jne .L_string_equals_false\n"
        << "    mov rcx, rax\n"
        << "    mov r8, [rdi + 16]\n"
        << "    mov r9, [rsi + 16]\n"
        << ".L_string_equals_loop:\n"
        << "    test rcx, rcx\n"
        << "    je .L_string_equals_true\n"
        << "    mov al, [r8]\n"
        << "    cmp al, [r9]\n"
        << "    jne .L_string_equals_false\n"
        << "    inc r8\n"
        << "    inc r9\n"
        << "    dec rcx\n"
        << "    jmp .L_string_equals_loop\n"
        << ".L_string_equals_true:\n"
        << "    mov rax, 3\n"
        << "    ret\n"
        << ".L_string_equals_false:\n"
        << "    mov rax, 1\n"
        << "    ret\n\n";
    out << "Runtime_stringStartsWith:\n"
        << "    mov rax, [rsi + 8]\n"
        << "    cmp qword [rdi + 8], rax\n"
        << "    jl .L_string_starts_false\n"
        << "    mov rcx, rax\n"
        << "    mov r8, [rdi + 16]\n"
        << "    mov r9, [rsi + 16]\n"
        << ".L_string_starts_loop:\n"
        << "    test rcx, rcx\n"
        << "    je .L_string_starts_true\n"
        << "    mov al, [r8]\n"
        << "    cmp al, [r9]\n"
        << "    jne .L_string_starts_false\n"
        << "    inc r8\n"
        << "    inc r9\n"
        << "    dec rcx\n"
        << "    jmp .L_string_starts_loop\n"
        << ".L_string_starts_true:\n"
        << "    mov rax, 3\n"
        << "    ret\n"
        << ".L_string_starts_false:\n"
        << "    mov rax, 1\n"
        << "    ret\n\n";
    out << "Runtime_stringEndsWith:\n"
        << "    mov rax, [rsi + 8]\n"
        << "    mov rbx, [rdi + 8]\n"
        << "    cmp rbx, rax\n"
        << "    jl .L_string_ends_false\n"
        << "    mov rcx, rax\n"
        << "    mov r8, [rdi + 16]\n"
        << "    add r8, rbx\n"
        << "    sub r8, rax\n"
        << "    mov r9, [rsi + 16]\n"
        << ".L_string_ends_loop:\n"
        << "    test rcx, rcx\n"
        << "    je .L_string_ends_true\n"
        << "    mov al, [r8]\n"
        << "    cmp al, [r9]\n"
        << "    jne .L_string_ends_false\n"
        << "    inc r8\n"
        << "    inc r9\n"
        << "    dec rcx\n"
        << "    jmp .L_string_ends_loop\n"
        << ".L_string_ends_true:\n"
        << "    mov rax, 3\n"
        << "    ret\n"
        << ".L_string_ends_false:\n"
        << "    mov rax, 1\n"
        << "    ret\n\n";
    out << "Runtime_stringIndexOf:\n"
        << "    mov r10, rdi\n"
        << "    mov r11, rsi\n"
        << "    mov r8, [r10 + 8]\n"
        << "    mov r9, [r11 + 8]\n"
        << "    test r9, r9\n"
        << "    je .L_string_index_found_zero\n"
        << "    cmp r9, r8\n"
        << "    jg .L_string_index_not_found\n"
        << "    mov rbx, r8\n"
        << "    sub rbx, r9\n"
        << "    xor rcx, rcx\n"
        << ".L_string_index_outer:\n"
        << "    cmp rcx, rbx\n"
        << "    jg .L_string_index_not_found\n"
        << "    xor rdx, rdx\n"
        << "    mov rdi, [r10 + 16]\n"
        << "    add rdi, rcx\n"
        << "    mov rsi, [r11 + 16]\n"
        << ".L_string_index_inner:\n"
        << "    cmp rdx, r9\n"
        << "    jge .L_string_index_found\n"
        << "    mov al, [rdi + rdx]\n"
        << "    cmp al, [rsi + rdx]\n"
        << "    jne .L_string_index_next\n"
        << "    inc rdx\n"
        << "    jmp .L_string_index_inner\n"
        << ".L_string_index_next:\n"
        << "    inc rcx\n"
        << "    jmp .L_string_index_outer\n"
        << ".L_string_index_found:\n"
        << "    mov rax, rcx\n"
        << "    shl rax, 1\n"
        << "    or rax, 1\n"
        << "    ret\n"
        << ".L_string_index_found_zero:\n"
        << "    mov rax, 1\n"
        << "    ret\n"
        << ".L_string_index_not_found:\n"
        << "    mov rax, -1\n"
        << "    ret\n\n";
    out << "Runtime_stringConcat:\n"
        << "    mov r10, rdi\n"
        << "    mov r11, rsi\n"
        << "    mov r8, [r10 + 8]\n"
        << "    mov r9, [r11 + 8]\n"
        << "    mov rdi, r8\n"
        << "    add rdi, r9\n"
        << "    add rdi, 24\n"
        << "    call Runtime_alloc\n"
        << "    mov rbx, rax\n"
        << "    mov qword [rbx], 0\n"
        << "    mov rax, r8\n"
        << "    add rax, r9\n"
        << "    mov [rbx + 8], rax\n"
        << "    lea rdx, [rbx + 24]\n"
        << "    mov [rbx + 16], rdx\n"
        << "    xor rcx, rcx\n"
        << "    mov rsi, [r10 + 16]\n"
        << ".L_string_concat_left:\n"
        << "    cmp rcx, r8\n"
        << "    jge .L_string_concat_right_start\n"
        << "    mov al, [rsi + rcx]\n"
        << "    mov [rdx + rcx], al\n"
        << "    inc rcx\n"
        << "    jmp .L_string_concat_left\n"
        << ".L_string_concat_right_start:\n"
        << "    xor rcx, rcx\n"
        << "    mov rsi, [r11 + 16]\n"
        << "    lea rdi, [rdx + r8]\n"
        << ".L_string_concat_right:\n"
        << "    cmp rcx, r9\n"
        << "    jge .L_string_concat_done\n"
        << "    mov al, [rsi + rcx]\n"
        << "    mov [rdi + rcx], al\n"
        << "    inc rcx\n"
        << "    jmp .L_string_concat_right\n"
        << ".L_string_concat_done:\n"
        << "    mov rax, rbx\n"
        << "    ret\n\n";
    out << "Runtime_stringToInt:\n"
        << "    mov rdx, [rdi + 8]\n"
        << "    mov rsi, [rdi + 16]\n"
        << "    test rdx, rdx\n"
        << "    je Runtime_parse_error\n"
        << "    xor rax, rax\n"
        << "    xor rcx, rcx\n"
        << "    xor r8, r8\n"
        << "    cmp byte [rsi], 0x2d\n"
        << "    jne .L_string_to_int_loop\n"
        << "    mov r8, 1\n"
        << "    inc rcx\n"
        << "    cmp rcx, rdx\n"
        << "    je Runtime_parse_error\n"
        << ".L_string_to_int_loop:\n"
        << "    cmp rcx, rdx\n"
        << "    jge .L_string_to_int_done\n"
        << "    movzx r9, byte [rsi + rcx]\n"
        << "    cmp r9b, 0x30\n"
        << "    jb Runtime_parse_error\n"
        << "    cmp r9b, 0x39\n"
        << "    ja Runtime_parse_error\n"
        << "    imul rax, rax, 10\n"
        << "    sub r9, 0x30\n"
        << "    add rax, r9\n"
        << "    inc rcx\n"
        << "    jmp .L_string_to_int_loop\n"
        << ".L_string_to_int_done:\n"
        << "    test r8, r8\n"
        << "    jz .L_string_to_int_tag\n"
        << "    neg rax\n"
        << ".L_string_to_int_tag:\n"
        << "    shl rax, 1\n"
        << "    or rax, 1\n"
        << "    ret\n\n";
    out << "Runtime_stringToCharArray:\n"
        << "    mov r11, [rdi + 8]\n"
        << "    mov r10, [rdi + 16]\n"
        << "    lea rdi, [r11 * 8 + 16]\n"
        << "    call Runtime_alloc\n"
        << "    mov rbx, rax\n"
        << "    mov qword [rbx], 0\n"
        << "    mov rax, r11\n"
        << "    shl rax, 1\n"
        << "    or rax, 1\n"
        << "    mov [rbx + 8], rax\n"
        << "    xor rcx, rcx\n"
        << ".L_string_to_char_array_loop:\n"
        << "    cmp rcx, r11\n"
        << "    jge .L_string_to_char_array_wrap\n"
        << "    movzx rax, byte [r10 + rcx]\n"
        << "    shl rax, 1\n"
        << "    or rax, 1\n"
        << "    mov [rbx + 16 + rcx * 8], rax\n"
        << "    inc rcx\n"
        << "    jmp .L_string_to_char_array_loop\n"
        << ".L_string_to_char_array_wrap:\n"
        << "    mov rdi, 16\n"
        << "    call Runtime_alloc\n"
        << "    mov qword [rax], 0\n"
        << "    mov [rax + 8], rbx\n"
        << "    ret\n\n";
    out << "Runtime_stringSubstring:\n"
        << "    mov r10, rdi\n"
        << "    mov r8, rsi\n"
        << "    sar r8, 1\n"
        << "    mov r9, rdx\n"
        << "    sar r9, 1\n"
        << "    cmp r8, 0\n"
        << "    jl Runtime_bounds_error\n"
        << "    cmp r9, r8\n"
        << "    jl Runtime_bounds_error\n"
        << "    cmp r9, [r10 + 8]\n"
        << "    jg Runtime_bounds_error\n"
        << "    mov r11, r9\n"
        << "    sub r11, r8\n"
        << "    mov rdi, r11\n"
        << "    add rdi, 24\n"
        << "    call Runtime_alloc\n"
        << "    mov rbx, rax\n"
        << "    mov qword [rbx], 0\n"
        << "    mov [rbx + 8], r11\n"
        << "    lea rdx, [rbx + 24]\n"
        << "    mov [rbx + 16], rdx\n"
        << "    mov rsi, [r10 + 16]\n"
        << "    add rsi, r8\n"
        << "    xor rcx, rcx\n"
        << ".L_string_substring_loop:\n"
        << "    cmp rcx, r11\n"
        << "    jge .L_string_substring_done\n"
        << "    mov al, [rsi + rcx]\n"
        << "    mov [rdx + rcx], al\n"
        << "    inc rcx\n"
        << "    jmp .L_string_substring_loop\n"
        << ".L_string_substring_done:\n"
        << "    mov rax, rbx\n"
        << "    ret\n\n";
    out << "Runtime_stringRepeat:\n"
        << "    mov r10, rdi\n"
        << "    mov r11, [r10 + 8]\n"
        << "    mov r12, rsi\n"
        << "    sar r12, 1\n"
        << "    cmp r12, 0\n"
        << "    jl Runtime_bounds_error\n"
        << "    mov rax, r11\n"
        << "    imul rax, r12\n"
        << "    mov rdi, rax\n"
        << "    add rdi, 24\n"
        << "    call Runtime_alloc\n"
        << "    mov rbx, rax\n"
        << "    mov qword [rbx], 0\n"
        << "    mov rax, r11\n"
        << "    imul rax, r12\n"
        << "    mov [rbx + 8], rax\n"
        << "    lea r9, [rbx + 24]\n"
        << "    mov [rbx + 16], r9\n"
        << "    xor r13, r13\n"
        << ".L_string_repeat_outer:\n"
        << "    cmp r13, r12\n"
        << "    jge .L_string_repeat_done\n"
        << "    mov r8, [r10 + 16]\n"
        << "    xor rcx, rcx\n"
        << ".L_string_repeat_inner:\n"
        << "    cmp rcx, r11\n"
        << "    jge .L_string_repeat_next\n"
        << "    mov al, [r8 + rcx]\n"
        << "    mov [r9], al\n"
        << "    inc r9\n"
        << "    inc rcx\n"
        << "    jmp .L_string_repeat_inner\n"
        << ".L_string_repeat_next:\n"
        << "    inc r13\n"
        << "    jmp .L_string_repeat_outer\n"
        << ".L_string_repeat_done:\n"
        << "    mov rax, rbx\n"
        << "    ret\n\n";
    out << "Runtime_stringTrim:\n"
        << "    mov r10, rdi\n"
        << "    mov r11, [r10 + 8]\n"
        << "    mov r12, [r10 + 16]\n"
        << "    xor r8, r8\n"
        << ".L_string_trim_left:\n"
        << "    cmp r8, r11\n"
        << "    jge .L_string_trim_empty\n"
        << "    mov al, [r12 + r8]\n"
        << "    cmp al, 32\n"
        << "    je .L_string_trim_left_next\n"
        << "    cmp al, 9\n"
        << "    je .L_string_trim_left_next\n"
        << "    cmp al, 10\n"
        << "    je .L_string_trim_left_next\n"
        << "    cmp al, 13\n"
        << "    jne .L_string_trim_right_start\n"
        << ".L_string_trim_left_next:\n"
        << "    inc r8\n"
        << "    jmp .L_string_trim_left\n"
        << ".L_string_trim_right_start:\n"
        << "    mov r9, r11\n"
        << "    dec r9\n"
        << ".L_string_trim_right:\n"
        << "    cmp r9, r8\n"
        << "    jl .L_string_trim_empty\n"
        << "    mov al, [r12 + r9]\n"
        << "    cmp al, 32\n"
        << "    je .L_string_trim_right_next\n"
        << "    cmp al, 9\n"
        << "    je .L_string_trim_right_next\n"
        << "    cmp al, 10\n"
        << "    je .L_string_trim_right_next\n"
        << "    cmp al, 13\n"
        << "    jne .L_string_trim_copy_start\n"
        << ".L_string_trim_right_next:\n"
        << "    dec r9\n"
        << "    jmp .L_string_trim_right\n"
        << ".L_string_trim_copy_start:\n"
        << "    mov r13, r9\n"
        << "    sub r13, r8\n"
        << "    inc r13\n"
        << "    jmp .L_string_trim_alloc\n"
        << ".L_string_trim_empty:\n"
        << "    xor r13, r13\n"
        << ".L_string_trim_alloc:\n"
        << "    mov rdi, r13\n"
        << "    add rdi, 24\n"
        << "    call Runtime_alloc\n"
        << "    mov rbx, rax\n"
        << "    mov qword [rbx], 0\n"
        << "    mov [rbx + 8], r13\n"
        << "    lea rdx, [rbx + 24]\n"
        << "    mov [rbx + 16], rdx\n"
        << "    add r12, r8\n"
        << "    xor rcx, rcx\n"
        << ".L_string_trim_copy:\n"
        << "    cmp rcx, r13\n"
        << "    jge .L_string_trim_done\n"
        << "    mov al, [r12 + rcx]\n"
        << "    mov [rdx + rcx], al\n"
        << "    inc rcx\n"
        << "    jmp .L_string_trim_copy\n"
        << ".L_string_trim_done:\n"
        << "    mov rax, rbx\n"
        << "    ret\n\n";
    out << "Runtime_stringSplit:\n"
        << "    mov r10, rdi\n"
        << "    mov r11, rsi\n"
        << "    mov r12, [r10 + 8]\n"
        << "    mov r13, [r11 + 8]\n"
        << "    mov r14, [r10 + 16]\n"
        << "    mov r15, [r11 + 16]\n"
        << "    test r13, r13\n"
        << "    je .L_string_split_empty_separator\n"
        << "    mov r8, 1\n"
        << "    xor r9, r9\n"
        << ".L_string_split_count_outer:\n"
        << "    mov rax, r9\n"
        << "    add rax, r13\n"
        << "    cmp rax, r12\n"
        << "    jg .L_string_split_allocate\n"
        << "    xor rcx, rcx\n"
        << ".L_string_split_count_inner:\n"
        << "    cmp rcx, r13\n"
        << "    jge .L_string_split_count_match\n"
        << "    mov rax, r14\n"
        << "    add rax, r9\n"
        << "    mov al, [rax + rcx]\n"
        << "    cmp al, [r15 + rcx]\n"
        << "    jne .L_string_split_count_next\n"
        << "    inc rcx\n"
        << "    jmp .L_string_split_count_inner\n"
        << ".L_string_split_count_match:\n"
        << "    inc r8\n"
        << "    add r9, r13\n"
        << "    jmp .L_string_split_count_outer\n"
        << ".L_string_split_count_next:\n"
        << "    inc r9\n"
        << "    jmp .L_string_split_count_outer\n"
        << ".L_string_split_allocate:\n"
        << "    lea rdi, [r8 * 8 + 16]\n"
        << "    call Runtime_alloc\n"
        << "    mov rbx, rax\n"
        << "    mov qword [rbx], 0\n"
        << "    mov rax, r8\n"
        << "    shl rax, 1\n"
        << "    or rax, 1\n"
        << "    mov [rbx + 8], rax\n"
        << "    xor r8, r8\n"
        << "    xor r9, r9\n"
        << "    xor rdx, rdx\n"
        << ".L_string_split_fill_outer:\n"
        << "    mov rax, r9\n"
        << "    add rax, r13\n"
        << "    cmp rax, r12\n"
        << "    jg .L_string_split_fill_final\n"
        << "    xor rcx, rcx\n"
        << ".L_string_split_fill_inner:\n"
        << "    cmp rcx, r13\n"
        << "    jge .L_string_split_fill_match\n"
        << "    mov rax, r14\n"
        << "    add rax, r9\n"
        << "    mov al, [rax + rcx]\n"
        << "    cmp al, [r15 + rcx]\n"
        << "    jne .L_string_split_fill_next\n"
        << "    inc rcx\n"
        << "    jmp .L_string_split_fill_inner\n"
        << ".L_string_split_fill_match:\n"
        << "    call Runtime_stringSplitMakeSegment\n"
        << "    add r9, r13\n"
        << "    mov r8, r9\n"
        << "    jmp .L_string_split_fill_outer\n"
        << ".L_string_split_fill_next:\n"
        << "    inc r9\n"
        << "    jmp .L_string_split_fill_outer\n"
        << ".L_string_split_fill_final:\n"
        << "    mov r9, r12\n"
        << "    call Runtime_stringSplitMakeSegment\n"
        << "    jmp .L_string_split_wrap\n"
        << ".L_string_split_empty_separator:\n"
        << "    mov r8, r12\n"
        << "    lea rdi, [r8 * 8 + 16]\n"
        << "    call Runtime_alloc\n"
        << "    mov rbx, rax\n"
        << "    mov qword [rbx], 0\n"
        << "    mov rax, r8\n"
        << "    shl rax, 1\n"
        << "    or rax, 1\n"
        << "    mov [rbx + 8], rax\n"
        << "    xor r8, r8\n"
        << "    xor rdx, rdx\n"
        << ".L_string_split_chars_loop:\n"
        << "    cmp r8, r12\n"
        << "    jge .L_string_split_wrap\n"
        << "    mov r9, r8\n"
        << "    inc r9\n"
        << "    call Runtime_stringSplitMakeSegment\n"
        << "    mov r8, r9\n"
        << "    jmp .L_string_split_chars_loop\n"
        << ".L_string_split_wrap:\n"
        << "    mov rdi, 16\n"
        << "    call Runtime_alloc\n"
        << "    mov qword [rax], 0\n"
        << "    mov [rax + 8], rbx\n"
        << "    ret\n\n";
    out << "Runtime_stringSplitMakeSegment:\n"
        << "    mov rax, r9\n"
        << "    sub rax, r8\n"
        << "    mov rdi, rax\n"
        << "    add rdi, 24\n"
        << "    push r8\n"
        << "    push r9\n"
        << "    push rdx\n"
        << "    call Runtime_alloc\n"
        << "    pop rdx\n"
        << "    pop r9\n"
        << "    pop r8\n"
        << "    mov rsi, rax\n"
        << "    mov qword [rsi], 0\n"
        << "    mov rax, r9\n"
        << "    sub rax, r8\n"
        << "    mov [rsi + 8], rax\n"
        << "    lea rdi, [rsi + 24]\n"
        << "    mov [rsi + 16], rdi\n"
        << "    xor rcx, rcx\n"
        << ".L_string_split_segment_copy:\n"
        << "    cmp rcx, [rsi + 8]\n"
        << "    jge .L_string_split_segment_done\n"
        << "    mov rax, r14\n"
        << "    add rax, r8\n"
        << "    mov al, [rax + rcx]\n"
        << "    mov [rdi + rcx], al\n"
        << "    inc rcx\n"
        << "    jmp .L_string_split_segment_copy\n"
        << ".L_string_split_segment_done:\n"
        << "    mov [rbx + 16 + rdx * 8], rsi\n"
        << "    inc rdx\n"
        << "    ret\n\n";
    out << "Int_method_toString:\n"
        << "    mov r10, rdi\n"
        << "    mov rdi, 56\n"
        << "    call Runtime_alloc\n"
        << "    mov rbx, rax\n"
        << "    mov rax, r10\n"
        << "    sar rax, 1\n"
        << "    mov qword [rbx], 0\n"
        << "    mov rcx, 10\n"
        << "    lea rsi, [rbx + 56]\n"
        << "    xor r8, r8\n"
        << "    xor r9, r9\n"
        << "    test rax, rax\n"
        << "    jge .L_str_abs_ready\n"
        << "    neg rax\n"
        << "    mov r9, 1\n"
        << ".L_str_abs_ready:\n"
        << "    test rax, rax\n"
        << "    jnz .L_loop_str\n"
        << "    dec rsi\n"
        << "    inc r8\n"
        << "    mov byte [rsi], 0x30\n"
        << "    jmp .L_str_sign\n"
        << ".L_loop_str:\n"
        << "    dec rsi\n"
        << "    inc r8\n"
        << "    cqo\n"
        << "    idiv rcx\n"
        << "    add dl, 0x30\n"
        << "    mov [rsi], dl\n"
        << "    test rax, rax\n"
        << "    jnz .L_loop_str\n"
        << ".L_str_sign:\n"
        << "    test r9, r9\n"
        << "    jz .L_str_done\n"
        << "    dec rsi\n"
        << "    inc r8\n"
        << "    mov byte [rsi], 0x2d\n"
        << ".L_str_done:\n"
        << "    mov [rbx + 8], r8\n"
        << "    mov [rbx + 16], rsi\n"
        << "    mov rax, rbx\n"
        << "    ret\n\n";
}
}
